# Generated by Django 4.2.1 on 2023-05-29 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedreward',
            name='retrieved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivedreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reward', to='reward.reward'),
        ),
    ]
