# Generated by Django 4.2.1 on 2023-05-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='flag',
            field=models.CharField(choices=[('visa', 'visa'), ('mastercard', 'mastercard'), ('elo', 'elo')], default='visa', max_length=30),
        ),
    ]
